In [1]:
!git clone https://github.com/codebasics/py.git

Cloning into 'py'...
remote: Enumerating objects: 2910, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 2910 (delta 0), reused 2 (delta 0), pack-reused 2904
Receiving objects: 100% (2910/2910), 196.66 MiB | 23.27 MiB/s, done.
Resolving deltas: 100% (1121/1121), done.
Updating files: 100% (1388/1388), done.

machine learning with python : save and load trained model

In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [3]:
df_home_price=pd.read_csv("/content/py/ML/4_save_model/homeprices.csv")

In [4]:
df_home_price

   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [16]:
model_to_predict=linear_model.LinearRegression()
model_to_predict.fit(df_home_price[['area']],df_home_price[['price']])

LinearRegression()

In [17]:
model_to_predict.coef_

array([[135.78767123]])

In [18]:
model_to_predict.intercept_

array([180616.43835616])

In [19]:
df_home_price

   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [20]:
model_to_predict.predict([[3000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[587979.45205479]])

In [21]:
import pickle as pk

In [22]:
with open('model_pk','wb') as file :
  pk.dump(model_to_predict,file)

In [24]:
with open('model_pk','rb') as file :
  my_predictor_model=pk.load(file)

In [27]:
my_predictor_model.predict([[300]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[221352.73972603]])

In [28]:
my_predictor_model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[859554.79452055]])

'model using joblib' was not found in history, as a file, url, nor in the user namespace.

'model using joblib' was not found in history, as a file, url, nor in the user namespace.

save train model using joblib

In [32]:
!pip install sklearn

Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [35]:
import joblib

In [36]:
joblib.dump(model_to_predict,'model_pd_joblib')

['model_pd_joblib']

In [37]:
model_lib=joblib.load("model_pd_joblib")

In [38]:
model_lib.coef_

array([[135.78767123]])

In [39]:
model_lib.intercept_

array([180616.43835616])

In [40]:
model_lib.predict([[6000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[995342.46575342]])

let's make model for airlines data

In [52]:
df_airlines=pd.read_csv("/content/airlines_data (1).csv")

In [53]:
df_airlines.head()

,Aircraft,AirlineName,CabinType,DateFlown,DatePub,EntertainmentRating,FoodRating,GroundServiceRating,OriginCountry,OverallScore,...,Route,SeatComfortRating,ServiceRating,Slug,Title,TravelType,TripVerified,ValueRating,WifiRating,unique_id
0,NaN,AB Aviation,Economy Class,Nov-19,11th November 2019,0,4,4,Netherlands,9.0,...,Moroni to Moheli,4,5,ab-aviation,pretty decent airline,Solo Leisure,Trip Verified,3,0,d3b260fb-268b-4399-8a9b-2804825902c6
1,E120,AB Aviation,Economy Class,Jun-19,25th June 2019,0,1,1,UnitedKingdom,1.0,...,Moroni to Anjouan,2,2,ab-aviation,Not a good airline,Solo Leisure,Trip Verified,2,0,307711df-268f-4698-97b8-45729b7d972e
2,Embraer E120,AB Aviation,Economy Class,Jun-19,25th June 2019,0,1,1,UnitedKingdom,1.0,...,Anjouan to Dzaoudzi,2,1,ab-aviation,flight was fortunately short,Solo Leisure,Trip Verified,2,0,82bd2602-171d-4724-bde0-90b71621cdcf
3,NaN,Aerocaribbean,Economy Class,NaN,31st December 2010,0,0,0,Denmark,8.0,...,NaN,0,0,aerocaribbean,Aerocaribbean customer review,NaN,NaN,4,0,a927beb4-6244-4f5c-9dc3-09890aa3e616
4,NaN,Aerocaribbean,NaN,NaN,25th November 2010,0,0,0,UnitedKingdom,1.0,...,NaN,0,0,aerocaribbean,Aerocaribbean customer review,NaN,NaN,0,0,d7bea425-c58a-4a7e-8269-02e0e6516633

In [54]:
df_airlines

,Aircraft,AirlineName,CabinType,DateFlown,DatePub,EntertainmentRating,FoodRating,GroundServiceRating,OriginCountry,OverallScore,...,Route,SeatComfortRating,ServiceRating,Slug,Title,TravelType,TripVerified,ValueRating,WifiRating,unique_id
0,NaN,AB Aviation,Economy Class,Nov-19,11th November 2019,0,4,4,Netherlands,9.0,...,Moroni to Moheli,4,5,ab-aviation,pretty decent airline,Solo Leisure,Trip Verified,3,0,d3b260fb-268b-4399-8a9b-2804825902c6
1,E120,AB Aviation,Economy Class,Jun-19,25th June 2019,0,1,1,UnitedKingdom,1.0,...,Moroni to Anjouan,2,2,ab-aviation,Not a good airline,Solo Leisure,Trip Verified,2,0,307711df-268f-4698-97b8-45729b7d972e
2,Embraer E120,AB Aviation,Economy Class,Jun-19,25th June 2019,0,1,1,UnitedKingdom,1.0,...,Anjouan to Dzaoudzi,2,1,ab-aviation,flight was fortunately short,Solo Leisure,Trip Verified,2,0,82bd2602-171d-4724-bde0-90b71621cdcf
3,NaN,Aerocaribbean,Economy Class,NaN,31st December 2010,0,0,0,Denmark,8.0,...,NaN,0,0,aerocaribbean,Aerocaribbean customer review,NaN,NaN,4,0,a927beb4-6244-4f5c-9dc3-09890aa3e616
4,NaN,Aerocaribbean,NaN,NaN,25th November 2010,0,0,0,UnitedKingdom,1.0,...,NaN,0,0,aerocaribbean,Aerocaribbean customer review,NaN,NaN,0,0,d7bea425-c58a-4a7e-8269-02e0e6516633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,NaN,Aerolineas Argentinas,Economy Class,NaN,19th April 2011,0,0,0,Australia,1.0,...,NaN,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,3ef8aff8-a6c2-40aa-855e-2fd238ee9b6e
451,NaN,Aerolineas Argentinas,Business Class,NaN,11th April 2011,0,0,0,Austria,7.0,...,NaN,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,4,0,4c4a3834-c130-4adf-8055-126e38365ba5
452,NaN,Aerolineas Argentinas,Economy Class,NaN,7th April 2011,0,0,0,Colombia,NaN,...,NaN,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,1fcac8dd-ef97-4a40-acda-fa882918e117
453,NaN,Aerolineas Argentinas,Economy Class,NaN,6th April 2011,0,0,0,NewZealand,3.0,...,NaN,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,9a132d77-e564-4114-9f56-3370d5491cb5
454,NaN,Aerolineas Argentinas,Economy Class,NaN,3rd April 2011,0,0,0,Netherlands,7.0,...,NaN,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,7fb914c0-2c89-410f-b0c3-3151a94a4ffa

In [71]:
df_airlines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 455 entries, 0 to 454
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   AirlineName          455 non-null    object
 1   CabinType            455 non-null    object
 2   DatePub              455 non-null    object
 3   EntertainmentRating  455 non-null    int64
 4   FoodRating           455 non-null    int64
 5   GroundServiceRating  455 non-null    int64
 6   OriginCountry        385 non-null    object
 7   OverallScore         388 non-null    float64
 8   Recommended          455 non-null    object
 9   Review               454 non-null    object
 10  SeatComfortRating    455 non-null    int64
 11  ServiceRating        455 non-null    int64
 12  Slug                 455 non-null    object
 13  Title                455 non-null    object
 14  TravelType           159 non-null    object
 15  TripVerified         90 non-null     object
 16  ValueRating          455 non-null    int64
 17  WifiRating           455 non-null    int64
 18  unique_id            455 non-null    object
dtypes: float64(1), int64(7), object(11)
memory usage: 67.7+ KB

In [45]:
df_airlines.shape

(455, 22)

In [46]:
df_airlines.Aircraft.unique()

array([nan, 'E120', 'Embraer E120 ', 'Dornier', 'BAe Jetstream', 'CR 900',
       'Bombardier CRJ', 'A319', 'ATR-72', 'CRJ700 / ATR72', 'CR9',
       'Canadair 700', 'CRJ900', 'CRJ-900', 'CRJ900 / A319', 'CRJ 900',
       'CRJ700', 'Ate', 'Embraer', 'Embraer 145', 'A330-200', 'A 320',
       'B0eing 737-800', 'A330', 'E190', 'Boeing 737', 'AR1256',
       '737-800', 'Boeing 737-800', 'Boeing 737-700  Boeing 737-8MAX',
       'Boeing 737-700', 'ERJ90', 'Boeing 737-800 ', 'A321',
       'Boeing 737-800 / A330-200', 'B737-800', 'A330-202',
       'Viking twin Otter', 'AT46', 'A340', 'Boeing 737-300', 'E-190',
       'A340-300', 'ATR 72-500', 'B767-300'], dtype=object)

In [47]:
from statistics import mode

In [59]:
df_airlines.drop('Aircraft',axis=1,inplace=True)

In [60]:
df_airlines

,AirlineName,CabinType,DateFlown,DatePub,EntertainmentRating,FoodRating,GroundServiceRating,OriginCountry,OverallScore,Recommended,...,Route,SeatComfortRating,ServiceRating,Slug,Title,TravelType,TripVerified,ValueRating,WifiRating,unique_id
0,AB Aviation,Economy Class,Nov-19,11th November 2019,0,4,4,Netherlands,9.0,yes,...,Moroni to Moheli,4,5,ab-aviation,pretty decent airline,Solo Leisure,Trip Verified,3,0,d3b260fb-268b-4399-8a9b-2804825902c6
1,AB Aviation,Economy Class,Jun-19,25th June 2019,0,1,1,UnitedKingdom,1.0,no,...,Moroni to Anjouan,2,2,ab-aviation,Not a good airline,Solo Leisure,Trip Verified,2,0,307711df-268f-4698-97b8-45729b7d972e
2,AB Aviation,Economy Class,Jun-19,25th June 2019,0,1,1,UnitedKingdom,1.0,no,...,Anjouan to Dzaoudzi,2,1,ab-aviation,flight was fortunately short,Solo Leisure,Trip Verified,2,0,82bd2602-171d-4724-bde0-90b71621cdcf
3,Aerocaribbean,Economy Class,NaN,31st December 2010,0,0,0,Denmark,8.0,yes,...,NaN,0,0,aerocaribbean,Aerocaribbean customer review,NaN,NaN,4,0,a927beb4-6244-4f5c-9dc3-09890aa3e616
4,Aerocaribbean,NaN,NaN,25th November 2010,0,0,0,UnitedKingdom,1.0,no,...,NaN,0,0,aerocaribbean,Aerocaribbean customer review,NaN,NaN,0,0,d7bea425-c58a-4a7e-8269-02e0e6516633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,Aerolineas Argentinas,Economy Class,NaN,19th April 2011,0,0,0,Australia,1.0,no,...,NaN,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,3ef8aff8-a6c2-40aa-855e-2fd238ee9b6e
451,Aerolineas Argentinas,Business Class,NaN,11th April 2011,0,0,0,Austria,7.0,yes,...,NaN,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,4,0,4c4a3834-c130-4adf-8055-126e38365ba5
452,Aerolineas Argentinas,Economy Class,NaN,7th April 2011,0,0,0,Colombia,NaN,no,...,NaN,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,1fcac8dd-ef97-4a40-acda-fa882918e117
453,Aerolineas Argentinas,Economy Class,NaN,6th April 2011,0,0,0,NewZealand,3.0,no,...,NaN,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,9a132d77-e564-4114-9f56-3370d5491cb5
454,Aerolineas Argentinas,Economy Class,NaN,3rd April 2011,0,0,0,Netherlands,7.0,yes,...,NaN,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,7fb914c0-2c89-410f-b0c3-3151a94a4ffa

In [62]:
df_airlines['AirlineName'].fillna(mode(df_airlines['AirlineName']),inplace=True)

In [63]:
df_airlines['CabinType'].fillna(mode(df_airlines['CabinType']),inplace=True)

In [64]:
df_airlines.drop('DateFlown',axis=1,inplace=True)

In [72]:
df_airlines

,AirlineName,CabinType,DatePub,EntertainmentRating,FoodRating,GroundServiceRating,OriginCountry,OverallScore,Recommended,Review,SeatComfortRating,ServiceRating,Slug,Title,TravelType,TripVerified,ValueRating,WifiRating,unique_id
0,AB Aviation,Economy Class,11th November 2019,0,4,4,Netherlands,9.0,yes,Moroni to Moheli. Turned out to be a pretty de...,4,5,ab-aviation,pretty decent airline,Solo Leisure,Trip Verified,3,0,d3b260fb-268b-4399-8a9b-2804825902c6
1,AB Aviation,Economy Class,25th June 2019,0,1,1,UnitedKingdom,1.0,no,Moroni to Anjouan. It is a very small airline....,2,2,ab-aviation,Not a good airline,Solo Leisure,Trip Verified,2,0,307711df-268f-4698-97b8-45729b7d972e
2,AB Aviation,Economy Class,25th June 2019,0,1,1,UnitedKingdom,1.0,no,Anjouan to Dzaoudzi. A very small airline and ...,2,1,ab-aviation,flight was fortunately short,Solo Leisure,Trip Verified,2,0,82bd2602-171d-4724-bde0-90b71621cdcf
3,Aerocaribbean,Economy Class,31st December 2010,0,0,0,Denmark,8.0,yes,Havana - Cayo Coco return. A one hour flight w...,0,0,aerocaribbean,Aerocaribbean customer review,NaN,NaN,4,0,a927beb4-6244-4f5c-9dc3-09890aa3e616
4,Aerocaribbean,Economy Class,25th November 2010,0,0,0,UnitedKingdom,1.0,no,Holguin to Havana last week. Okay apart from i...,0,0,aerocaribbean,Aerocaribbean customer review,NaN,NaN,0,0,d7bea425-c58a-4a7e-8269-02e0e6516633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,Aerolineas Argentinas,Economy Class,19th April 2011,0,0,0,Australia,1.0,no,Flight suspended in Aukland for 24hrs due to a...,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,3ef8aff8-a6c2-40aa-855e-2fd238ee9b6e
451,Aerolineas Argentinas,Business Class,11th April 2011,0,0,0,Austria,7.0,yes,MAD-EZE return. On the upper deck on the way t...,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,4,0,4c4a3834-c130-4adf-8055-126e38365ba5
452,Aerolineas Argentinas,Economy Class,7th April 2011,0,0,0,Colombia,NaN,no,Came To Argentina for vacations. The first fli...,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,1fcac8dd-ef97-4a40-acda-fa882918e117
453,Aerolineas Argentinas,Economy Class,6th April 2011,0,0,0,NewZealand,3.0,no,I've flown from Auckland to Sao Paulo and retu...,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,9a132d77-e564-4114-9f56-3370d5491cb5
454,Aerolineas Argentinas,Economy Class,3rd April 2011,0,0,0,Netherlands,7.0,yes,AEP-FTE via Ushuaia check in chaotic use web c...,0,0,aerolineas-argentinas,Aerolineas Argentinas customer review,NaN,NaN,1,0,7fb914c0-2c89-410f-b0c3-3151a94a4ffa

In [66]:
df_airlines['EntertainmentRating'].fillna(mode(df_airlines['EntertainmentRating']),inplace=True)

In [69]:
df_airlines['OriginCountry'].unique()

array(['Netherlands', 'UnitedKingdom', 'Denmark', nan, 'Italy',
       'Portugal', 'Serbia', 'Austria', 'Switzerland', 'Germany',
       'UnitedStates', 'France', 'Slovenia', 'CzechRepublic', 'Finland',
       'Singapore', 'Australia', 'Estonia', 'Poland', 'Turkey',
       'Malaysia', 'Canada', 'Greece', 'Spain', 'Ukraine', 'Macedonia',
       'Mexico', 'Chile', 'China', 'Iran', 'Ghana', 'Belgium', 'Lebanon',
       'Bolivia', 'Argentina', 'Brazil', 'Sweden', 'Thailand', 'India',
       'RussianFederation', 'UnitedArabEmirates', 'Jordan',
       'NetherlandsAntilles', 'Israel', 'Vietnam', 'Bermuda', 'Morocco',
       'Colombia', 'NewZealand', 'Norway', 'Bahamas'], dtype=object)

In [70]:
df_airlines.drop('Route',axis=1,inplace=True)